language: php

php:
    - 5.4
    - 5.5
    - 5.6

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer selfupdate

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

notifications:
    email:
        - alakhefifi@gmail.com
