name: tests

on:
    pull_request: ~
    push:
        branches:
            - master

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "7.1.3"
                    - "7.2"
                    - "7.4"
                    - "8.0"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Install dependencies
              run: composer install

            - name: Run PHPUnit tests
              run: |
                  ./vendor/bin/phpunit
